---
title: "Project 1, Part 4"
output: 
  rmdformats::robobook:
    css: "homework.css"
    highlight: pygments
link-citations: yes
---

**Due:** Friday, April 1, 12:00pm (noon) on Canvas

**Submission:** A template file is provided: [project_1_part_4_template.Rmd](https://sta112-s22.github.io/projects/project_1_part_4_template.Rmd)

Once you have completed the report, submit your 
knitted HTML file to Canvas.

# Overview

So far, you have used exploratory data analysis and linear regression with a single predictor to answer your research questions. The next step will be to add more variables to your model(s), to answer more in-depth questions.

When working with lots of variables, it is easy to fall down a rabbit hole exploring different models. To make sure you choose reasonable models that help you address your research questions, it is often helpful to plan out some steps of your analysis in advance. You do not have to stick to these steps completely, but having an idea of what you will do ahead of time is useful.

In this part of the project, you will come up with a plan for answering some research questions, and submit your plan to receive feedback. You do not have to actually do the analysis yet!

This project must be completed independently. See "Collaboration" below for more details.

# Data

The [College Scorecard](https://collegescorecard.ed.gov/), compiled by the US Department of Education, is meant to be a tool for college applicants to compare different institutions. In this project, you will work with data from the scorecard to advise a high school senior on choosing a college. (We will use data that are several years old, so may be slightly out of date, but we will hope that the same general trends are still true today).

## Variables

The dataset provided for this project contains the following columns:

* `INSTNM`: school name
* `STABBR`: state in which the school is located
* `CONTROL`: whether the school is public or private
* `SATVRMID`: midpoint of SAT critical reading scores of students attending the school
* `SATMTMID`: midpoint of SAT math scores
* `SATWRMID`: midpoint of SAT writing scores
* `ACTCMMID`: midpoint of the ACT cumulative scores
* `ACTENMID`: midpoint of ACT English scores
* `ACTMTMID`: midpoint of ACT math scores
* `ACTWRMID`: midpoint of ACT writing scores
* `UGDS`: number of undergraduate students at the school
* `NPT4`: average cost to attend the school
* `PCTFLOAN`: fraction of undergraduates receiving a federal student loan
* `MD_EARN_WNE_P10`: median salary of students 10 years after graduation
* `GRAD_DEBT_MDN_SUPP`: median debt of graduated students
* `RPY_3YR_RT_SUPP`: proportion of students who are actively repaying their loans 3 years after graduation
* `RPY_3YR_70`: whether the proportion of students actively repaying their loans 3 years after graduation is > 70% (1 = yes, 0 = no)

## Downloading the data

The data for this project is stored in a CSV file, and can be imported into R with the `read_csv` function in the `readr` package. The following code imports the data and saves it as a data frame called `scorecard`:

```r
scorecard <- read_csv("https://sta112-s22.github.io/projects/scorecard.csv")
```

This code is included in the setup chunk of the R Markdown template for the project.

# Research questions

For this project, suppose you have been approached by a high school senior applying to college. They are looking through the college scorecard data, and they have some questions for you about the value of different schools. 

1. Do students who graduate from more expensive schools earn more money after graduation, after accounting for student debt, school type (public or private), and the test scores of enrolled students?

2. Is the relationship between school cost and graduate earnings the same for public and private schools, after accounting for student debt and the test scores of enrolled students?


# Content

Your written report for Part 4 will contain the following sections: Modeling, Assumptions and Diagnostics, and Inference. 

## Modeling

Write a short paragraph in which you:

* Describe the model(s) you will use to answer the research questions (write down the equation of the population model(s))
* Explain why the model(s) allow you to answer the research questions

## Assumptions and Diagnostics

Write a paragraph in which you:

* Describe the assumptions made by your models
* Describe how you will assess these assumptions (e.g., diagnostic plots)

## Inference

Write a paragraph in which you describe how you will use the model(s) to answer the research questions. Make sure to:

* State the null and alternative hypotheses, in terms of one or more model parameters, for any hypothesis tests
* Describe the test you would use to test any hypotheses (t test? nested F test? what would the degrees of freedom be?)
* Explain whether you would calculate any confidence intervals
  
  
# Appearance and style

### Writing

The report should be written like an article or research paper: in full sentences and paragraphs, with headings for each section. You should not write your report with question numbers or as a list of bullet points. Scientific articles are generally written in third person, though "we" can also be acceptable ("we can see from Figure 1...") in some disciplines.

### Code

You do not need to run any code for this part of the project.

### Figures

You do not need to make any figures for this part of the project.

### Writing math in R Markdown

Doing things like writing down models often involve parameters. Parameters in statistics are generally represented as Greek letters. How can we write Greek letters and other mathematical notation in our Markdown file so they show up when we knit?

If you want to write mathematical notation, we need to tell Markdown, “Hey, we’re going to make a math symbol!” To do that, you use dollar signs. For instance, to make $\widehat{\beta}_1$, you simply put `$\widehathat{\beta}_1$` into the white space (not a chunk) in your Markdown.

Here are some examples of writing math, which you can adapt:

| Math | Code |
| --- | --- |
| $Y = \beta_0 + \beta_1 X + \varepsilon$ | `$Y = \beta_0 + \beta_1 X + \varepsilon$` |
| $\widehat{Y} = -2.2 + 3.7 X$ | `$\widehat{Y} = -2.2 + 3.7 X$` |
| $H_0: \beta_1 = 0$ | `$H_0: \beta_1 = 0$` |
| $H_A: \beta_1 \neq 0$ | `$H_0: \beta_1 \neq 0$` |
| $H_A: \beta_1 > 0$ | `$H_0: \beta_1 > 0$` |
| $H_A: \beta_1 < 0$ | `$H_0: \beta_1 < 0$` |

# Collaboration

One purpose of the projects is to capture your knowledge and understanding of statistics and data analysis. Unlike homework and lab assignments, this project must be completed on your own, without collaborating with other students. 

You may:

* ask the instructor for help
* use resources from the class notes and internet (Wikipedia, StackExchange, etc.)

You may not:

* work with another student on the project
* ask a TA or tutor (e.g., at the MSC) for help


