---
title: "Homework 7"
output: 
  rmdformats::robobook:
    css: "homework.css"
    highlight: pygments
link-citations: yes
editor_options: 
  chunk_output_type: console
---

**Due:** Monday, April 25, 12:00pm on Canvas


### Template

A template R Markdown file, which loads the data and packages you will need for the assignment, is provided: [hw_07_template.Rmd](https://sta112-s22.github.io/homework/hw_07_template.Rmd)

### Data

In this homework, you will look at a dataset of 3402 pitches thrown by MLB pitcher Clayton Kershaw in the 2013 season. The data is contained in the `Kershaw` data set, in the `Stat2Data` R package. We will focus on two specific variables for each pitch:

* `Result`: a negative result (a ball or a hit), or a positive result (a strike or an out)
* `EndSpeed`: the speed at which the ball crossed home plate (in mph)

Our goal is to investigate the relationship between pitch speed and result. Are faster pitches more successful (i.e., more likely to lead to a strike or an out)?

# Part I

Your friend is interested in analyzing the relationship between Clayton Kershaw's pitching speed and the result of the pitch. They fit a regression model, and send you the following report:

"There appears to be a positive relationship between the pitching speed and the outcome of the pitch (Figure 1). To summarize this relationship, we fit a simple linear regression with end speed as the predictor, and result as the response. The fitted line is shown in Figure 1, and the equation of the fitted line is $\widehat{\pi} = 0.157 + 0.0056 \ \text{EndSpeed}$, where $\pi = P(\text{Result} = 1)$."

```{r echo=F, message=F, warning=F, fig.cap="Figure 1: Pitch result vs. end speed for Clayton Kershaw.", fig.align='center', fig.width=5, fig.height=3}
library(tidyverse)
library(Stat2Data)
data("Kershaw")
Kershaw %>%
  mutate(Result = ifelse(Result == "Pos", 1, 0)) %>%
  ggplot(aes(x = EndSpeed, y = Result)) +
  geom_point() +
  geom_smooth(se=F, method="lm") +
  labs(x = "End speed (mph)", y = "Pitch result") +
  theme_bw()
```


:::{.question}
#### Question 1

Your friend has made a serious error in fitting this regression model. Explain to your friend what they have done wrong, why it is wrong, and how they should do it differently.
:::

# Part II

After reading your feedback from Part I, your friend decides to fit a logistic regression model instead. However, they are confused about logistic regression, and they ask you to help them.

:::{.question}
#### Question 2

Fit a logistic regression model for the relationship between Clayton Kershaw's pitching speed and pitch result. Report the equation of the fitted model.
:::

:::{.question}
#### Question 3

What is the associated change in the odds of a successful pitch (i.e., a strike or out) when pitching speed increases by 1 mph?
:::

:::{.question}
#### Question 4

Calculate the estimated *probability* of a successful pitch when pitching speed is 95 mph.
:::

:::{.question}
#### Question 5

Are faster pitches more likely to be successful? Carry out a hypothesis test.
:::