---
title: "Class Activity, January 31"
output: 
  tufte::tufte_html:
    css: "../labs/lab.css"
    tufte_variant: "envisioned"
    highlight: pygments
link-citations: yes
---

In this activity, you will practice calculating p-values and constructing confidence intervals for the slope of a regression line.

## Setup

This activity investigates the relationship between the wing length and weight of sparrows on Kent island. The data are contained in the `Sparrows` dataset from the `Stat2Data` package. Run the setup chunk in the template before you begin.

Download the activity template: [activity template](https://sta112-s22.github.io/class_activities/ca_lecture_9_template.Rmd)

## Questions

We are interested in whether there is a relationship between wing length and weight for sparrows. Our model is

$\text{wing length} = \beta_0 + \beta_1 \text{weight} + \varepsilon$

Under this model, "no relationship" means $\beta_1 = 0$. We will construct a confidence interval for $\beta_1$, and calculate a p-value for the hypotheses

$H_0: \beta_1 = 0$

$H_A: \beta_1 \neq 0$

1. Run the code below to fit the linear regression model, save it is `sparrow_lm`, and then summarize the results.

```r
sparrow_lm <- lm(WingLength ~ Weight, data = Sparrows)
summary(sparrow_lm)
```

2. From the output in 1, what is the estimate $\widehat{\beta}_1$ of the slope?

<SCRIPT>
function ShowAndHide(divid) {
    var x = document.getElementById(divid);
    if (x.style.display == 'none') {
        x.style.display = 'block';
    } else {
        x.style.display = 'none';
    }
}
</SCRIPT>

<BUTTON ONCLICK="ShowAndHide('q2_solution')">Solution</BUTTON>

<DIV ID="q2_solution" STYLE="display:none">
$\widehat{\beta}_1 = 1.313$
</DIV>

3. From the output in 1, what is the estimate $SE_{\widehat{\beta}_1}$ of the standard error of $\widehat{\beta}_1$?

<BUTTON ONCLICK="ShowAndHide('q3_solution')">Solution</BUTTON>

<DIV ID="q3_solution" STYLE="display:none">
$SE_{\widehat{\beta}_1} = 0.0976$
</DIV>

4. From the output in 1, what is the test statistic $t$? Confirm that $t = \dfrac{\widehat{\beta}_1}{SE_{\widehat{\beta}_1}}$.

<BUTTON ONCLICK="ShowAndHide('q4_solution')">Solution</BUTTON>

<DIV ID="q4_solution" STYLE="display:none">
$t = 13.46 \approx \dfrac{1.313}{0.0976}$ (answer is slightly different depending on when you round)
</DIV>

5. From the output in 1, what is the p-value for the hypotheses $H_0: \beta_1 = 0$ vs. $H_A: \beta_1 \neq 0$?

<BUTTON ONCLICK="ShowAndHide('q5_solution')">Solution</BUTTON>

<DIV ID="q5_solution" STYLE="display:none">
p-value $< 2\times 10^{-16}$. The observed slope is *very* unusual if there really is no relationship between wing length and weight, so we have strong evidence that there is a relationship between wing length and weight in the population of sparrows.
</DIV>

6. Now let's check the p-value manually. Fill in the code below to calculate the p-value using the `pt` function. Confirm that it agrees with exercise 5. Make sure to change the test statistic and the degrees of freedom. (Note: R just reports `< 2.2e-16` when p-values are below $2.2 \times 10^{-16}$).

```r
pt(..., df = ..., lower.tail = TRUE) + pt(..., df = ..., lower.tail = FALSE)
```

<BUTTON ONCLICK="ShowAndHide('q6_solution')">Solution</BUTTON>

<DIV ID="q6_solution" STYLE="display:none">
```r
pt(-13.463, df = 114, lower.tail = TRUE) + pt(13.463, df = 114, lower.tail = FALSE)
```

The resulting number is $2.623 \times 10^{-25}$, which is indeed less than $2.2 \times 10^{-16}$
</DIV>

:::{.question}
*What's going on here?*

The `pt` function calculates tail probabilities for a $t$ distribution (The `p` in `pt` stands for "probability", while the `t` indicates the $t$ distribution). The `df` argument allows you to specify the degrees of freedom (for simple linear regression, df = $n-2$). The `lower.tail` argument specifies whether you are calculating a left-tail or right-tail probability. For a two-sided test, we calculate a left-tail probability for $-|t|$, and a right-tail probability for $|t|$, and add them together. (Since the $t$-distribution is symmetric, we could also calculate one of them and multiply by 2).
:::

7. What if we wanted to test $H_0: \beta_1 = 0$ vs. $H_A: \beta_1 > 0$? Then we only need the right tail of the t-distribution to calculate the p-value. Adapt the code from question 6 to calculate the p-value for the new hypotheses.

<BUTTON ONCLICK="ShowAndHide('q7_solution')">Solution</BUTTON>

<DIV ID="q7_solution" STYLE="display:none">
```r
pt(13.463, df = 114, lower.tail = FALSE)
```
</DIV>

8. Next, we will want to calculate a confidence interval. But we need the critical value $t^*$. Fill in the code below to find $t^*$ for a 99% confidence interval:

```r
qt(..., df = ..., lower.tail = FALSE)
```

<BUTTON ONCLICK="ShowAndHide('q8_solution')">Solution</BUTTON>

<DIV ID="q8_solution" STYLE="display:none">
```r
qt(0.005, df = 114, lower.tail = FALSE)
```

Remember that for a 99% confidence interval, we want 0.5% *in each tail*, so we get the quantile for 0.005, rather than 0.01.
</DIV>

:::{.question}
*What's going on here?*

The `qt` function calculates quantiles for a $t$ distribution (The `q` in `qt` stands for "quantile", while the `t` indicates the $t$ distribution). The `df` argument allows you to specify the degrees of freedom (for simple linear regression, df = $n-2$).
:::

9. Using your answer to exercise 8, calculate a 99% confidence interval for the true slope $\beta_1$ of the relationship between wing length and weight. Remember that the confidence interval is given by

$\widehat{\beta}_1 \pm t^* SE_{\widehat{\beta}_1}$

<BUTTON ONCLICK="ShowAndHide('q9_solution')">Solution</BUTTON>

<DIV ID="q9_solution" STYLE="display:none">
```r
1.313 - 2.62*0.0976
1.313 + 2.62*0.0976
```

So we are 99% confident that an increase of 1g in weight is associated with an average increase in wing length of between 1.057mm and 1.569mm, in the population of sparrows.
</DIV>