---
---
---
title: "Class Activity, February 9"
author: "Your Name"
output: html_document
---

## Setup

Run the setup chunk:

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(Stat2Data)
library(tidyverse)
data("CountyHealth")
```

## Question 1

Fill in the code below to fit the linear regression model, and save the fitted model as `health_lm` in R:

```{r}
health_lm <- lm(... ~ ..., data = ...)
```


## Question 2

Run the code below to make a residual plot for the fitted model:

```{r}
CountyHealth %>%
  mutate(yhat = predict(health_lm),
         residuals = residuals(health_lm)) %>%
  ggplot(aes(x = yhat, y = residuals)) +
  geom_point() +
  geom_abline(slope = 0, intercept = 0, 
              color = "blue", lwd = 1.2) +
  labs(x = "Predicted number of doctors",
       y = "Residual") +
  theme_bw()
```

## Question 3

Run the code below to make a QQ plot for the fitted model:

```{r}
CountyHealth %>%
  mutate(residuals = residuals(health_lm)) %>%
  ggplot(aes(sample = residuals)) +
  geom_qq() +
  geom_qq_line() +
  labs(x = "Theoretical normal quantiles",
       y = "Observed residual quantiles") +
  theme_classic()
```


## Question 4




## Question 5


