---
title: "Class Activity, January 28"
output: 
  tufte::tufte_html:
    css: "lab.css"
    tufte_variant: "envisioned"
    highlight: pygments
link-citations: yes
---

In this activity, you will experiment with using least squares to fit simple linear regression with the `Sparrows` dataset. 

## Setup

The `Sparrows` data is contained in the `Stat2Data` package. This is the R package which contains the datasets from our textbook. We first need to install the `Stat2Data` package:

```r
install.packages("Stat2Data")
```

Now load the required packages into your R session:

```r
library(Stat2Data)
data(Sparrows)
library(tidyverse)
```

Finally, download the activity template: [activity template](https://sta112-s22.github.io/class_activities/ca_lecture_8_template.Rmd)

The activity template contains copies of the code and questions below. Run the setup chunk in the template before you begin.

There are two parts to the activity, which you will complete at different times during class today.

## Part I

The code in the chunk below lets you specify an intercept and slope for the regression line. It then plots a line with the specified intercept and slope, and reports the sum of squared residuals (SSE). Experiment with changing the intercept and slope, and observe how the plot and SSE change.

```r
# add values here!
est_intercept = ...
est_slope = ...

# plot
Sparrows %>%
  ggplot(aes(x = Weight, y = WingLength)) +
  geom_point() +
  geom_abline(intercept = est_intercept,
              slope = est_slope,
              color = "blue",
              lwd = 1.5)

# calculate sum of squared residuals
Sparrows %>%
  mutate(prediction = est_intercept + est_slope*Weight,
         residual = WingLength - prediction) %>%
  summarize(sum_sq_resid = sum(residual^2))
```

1. Which values give the smallest SSE?


## Part II

We can use the lm function to fit a linear regression in R. Run the following code:

```r
lm(WingLength ~ Weight, data = Sparrows)
```

2. What are the estimated slope and intercept?

<SCRIPT>
function ShowAndHide(divid) {
    var x = document.getElementById(divid);
    if (x.style.display == 'none') {
        x.style.display = 'block';
    } else {
        x.style.display = 'none';
    }
}
</SCRIPT>

<BUTTON ONCLICK="ShowAndHide('q1_solution')">Solution</BUTTON>

<DIV ID="q1_solution" STYLE="display:none">
$\widehat{\beta}_0 = 8.755$, $\widehat{\beta}_1 = 1.313$
</DIV>

3. What is the SSE when using the estimated slope and intercept from question 2? Confirm this SSE is smaller than for the different slopes and intercepts you tried in part I.

<BUTTON ONCLICK="ShowAndHide('q2_solution')">Solution</BUTTON>

<DIV ID="q2_solution" STYLE="display:none">
SSE = 627.51
</DIV>

4. If a sparrow has a weight of 10g, what is its predicted wing length from the estimated regression line?

<BUTTON ONCLICK="ShowAndHide('q3_solution')">Solution</BUTTON>

<DIV ID="q3_solution" STYLE="display:none">
$\widehat{\text{wing length}} = 8.755 + 1.313 \cdot 10 = 21.885$
</DIV>
