---
title: "Class Activity, January 21"
output: 
  tufte::tufte_html:
    css: "lab.css"
    tufte_variant: "envisioned"
    highlight: pygments
link-citations: yes
---

In this activity, you will practice using `dplyr` functions with the `flights` data from Homework 1. Work in groups to answer the questions below.

You may find the `dplyr` cheatsheet helpful: [cheat sheet](https://raw.githubusercontent.com/rstudio/cheatsheets/master/data-transformation.pdf)

## Setup

As with all class activities, there is nothing you will need to submit. However, in case it helps you work on the questions, an R Markdown template is provided for you: [activity template](https://sta112-f21.github.io/class_activities/ca_lecture_5_template.Rmd)

You will need to load the `nycflights13` and `tidyverse` packages. If you use the R Markdown template, those packages are included in the setup chunk, so you just need to run the setup chunk first.

## Questions

For the purposes of these questions, we will remove all rows from `flights` which contain NAs.

Flights departing late will probably arrive late. We can look at the relationship between departure delay and arrival delay with a scatterplot:

```{r, echo=F, message=F, warning=F, fig.align='center', fig.width=6, fig.height=4}
library(tidyverse)
library(nycflights13)

flights %>%
  drop_na() %>%
  sample_n(5000) %>%
  ggplot(aes(x = dep_delay,
             y = arr_delay)) +
  geom_point(size = 1.5) +
  labs(x = "Departure delay (minutes)",
       y = "Arrival delay (minutes)") +
  theme_bw() +
  theme(text = element_text(size=20))
```

One way to summarize the relationship between two quantitative variables is with the *correlation*, which measures the strength of the linear relationship between the two variables. Correlation is a number between -1 and 1; a correlation close to -1 indicates a strong negative relationship, while a correlation close to 1 indicates a strong positive relationship, and a correlation of 0 indicates no relationship.

1. In R, we calculate correlation with the *cor* function. Fill in the code below to calculate the correlation between departure delay and arrival delay:

```r
flights %>%
  drop_na() %>%
  summarize(delay_cor = cor(..., ...))
```

<SCRIPT>
function ShowAndHide(divid) {
    var x = document.getElementById(divid);
    if (x.style.display == 'none') {
        x.style.display = 'block';
    } else {
        x.style.display = 'none';
    }
}
</SCRIPT>

<BUTTON ONCLICK="ShowAndHide('q1_solution')">Solution</BUTTON>

<DIV ID="q1_solution" STYLE="display:none">
```r
flights %>%
  drop_na() %>%
  summarize(delay_cor = cor(dep_delay, arr_delay))
```
</DIV>

2. Does the correlation between departure delay and arrival delay depend on which airport the flight departs from? We can use the `group_by` function to group the data before calculating correlation. Fill in the code below to calculate the correlation for each airport (EWR, JFK, and LGA).

```r
flights %>%
  drop_na() %>%
  group_by(...) %>%
  summarize(delay_cor = cor(..., ...))
```

<BUTTON ONCLICK="ShowAndHide('q2_solution')">Solution</BUTTON>

<DIV ID="q2_solution" STYLE="display:none">
```r
flights %>%
  drop_na() %>%
  group_by(origin) %>%
  summarize(delay_cor = cor(dep_delay, arr_delay))
```
</DIV>

3. Flights departing late will probably arrive late. But sometimes pilots can make up for lost time during the flight. Let's create a new variable measuring the amount of time made up during each flight, and visualize its distribution with a histogram. Fill in the following code:

```r
flights %>%
  drop_na() %>%
  mutate(time_gained = ...) %>%
  ggplot(aes(x = ...)) +
  geom_histogram() +
  labs(x = "...",
       title = "...") +
  theme_bw()
```

<BUTTON ONCLICK="ShowAndHide('q3_solution')">Solution</BUTTON>

<DIV ID="q3_solution" STYLE="display:none">
```r
flights %>%
  drop_na() %>%
  mutate(time_gained = dep_delay - arr_delay) %>%
  ggplot(aes(x = time_gained)) +
  geom_histogram() +
  labs(x = "Time gained (minutes)",
       title = "Distribution of flight time gained") +
  theme_bw()
```
</DIV>

4. How does the amount of time gained vary across airlines? Fill in the following code to calculate the average time gained and the standard deviation of time gained for each airline.

```r
flights %>%
  drop_na() %>%
  mutate(time_gained = ...) %>%
  group_by(...) %>%
  summarize(avg_time_gained = ...,
            sd_time_gained = ...)
```

<BUTTON ONCLICK="ShowAndHide('q4_solution')">Solution</BUTTON>

<DIV ID="q4_solution" STYLE="display:none">
```r
flights %>%
  drop_na() %>%
  mutate(time_gained = dep_delay - arr_delay) %>%
  group_by(carrier) %>%
  summarize(avg_time_gained = mean(time_gained),
            sd_time_gained = sd(time_gained))
```
</DIV>

5. Now let's look more at the different airlines. Which airport is the most common departure airport for American Airlines (AA) flights? Fill in the following code.

```r
flights %>%
  filter(... == "AA") %>%
  count(...)
```

<BUTTON ONCLICK="ShowAndHide('q5_solution')">Solution</BUTTON>

<DIV ID="q5_solution" STYLE="display:none">
```r
flights %>%
  filter(carrier == "AA") %>%
  count(origin)
```
</DIV>

6. Occasionally, flights actually depart early. How many American Airlines flights departed early?

```r
flights %>%
  drop_na() %>%
  filter(carrier ..., dep_delay ...) %>%
  count()
```

<BUTTON ONCLICK="ShowAndHide('q6_solution')">Solution</BUTTON>

<DIV ID="q6_solution" STYLE="display:none">
```r
flights %>%
  drop_na() %>%
  filter(carrier == "AA", dep_delay < 0) %>%
  count()
```
</DIV>
