---
title: "Class Activity, March 30"
output: 
  tufte::tufte_html:
    css: "lab.css"
    tufte_variant: "envisioned"
    highlight: pygments
link-citations: yes
---


Biologists hypothesize that birds which live over a small area are less genetically diverse than birds which live over a large area, because a larger habitat allows species to be adapted to a wider range of environments, and because larger habitats help prevent interbreeding.

To investigate this hypothesis, they collected data on 387 different bird species. Each row in the data is a species, and for each species the researchers recorded the following variables:

* *genetic diversity*: a measure of genetic diversity. (Formally, they measured heterozygosity, the probability that for a randomly selected gene, the individual's alleles are different)
* *breeding range*: size of the spatial range over which this bird breeds, in units of 10,000 square km
* *mass*: average body mass (g)
* *latitude*: mid-point latitude of the species breeding range
* *migratory status*: whether the species migrates

The researchers want to model the relationship between breeding range and genetic diversity, and they want to know if this relationship depends on whether the species is migratory. Furthermore, they suspect that body size and latitude may also be related to genetic diversity and breeding range.

1. Write down a model which allows the researchers to address their research questions.
2. Using the model in Exercise 1, write down hypotheses which allow the researchers to test whether there is any relationship between breeding range and genetic diversity, after accounting for migratory status, body size, and latitude.
3. Which test can the researchers use for the hypotheses in Exercise 2? What are the degrees of freedom?
4. Using the model in Exercise 1, write down hypotheses which allow the researchers to test whether the slope of the relationship between breeding range and genetic diversity is different for migratory and non-migratory species, after accounting for body size and latitude.
5. Which test can the researchers use for the hypotheses in Exercise 4? What are the degrees of freedom?


